name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    permissions:
        contents: write
        discussions: write
        issues: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.21.2' # Укажите нужную версию CMake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .





      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install Pandoc and LaTeX
        run: |
          choco install pandoc
          choco install miktex

      - name: Build PDF
        run: |
          mkdir output
          pandoc README.md -o build/README.pdf

         
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0 # Укажите версию релиза (можно динамически генерировать)
        files: build/Debug/hello_world.exe # Путь к вашему исполняемому файлу
        files: build/README.pdf
        body: |
          Changes in this release...
          